import Head from 'next/head';
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Results from '../components/Results';
import requests from '../utils/requests';

export default function Home({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Movies App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header />
      {/* Navbar */}
      <Navbar />
      {/* Results */}
      <Results results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genr || 'fetchTrending';
  const request = await fetch(
    `${process.env.BASE_URL}${requests[genre].url}`
  ).then((response) => response.json());
  return {
    props: {
      results: request.results,
    },
  };
}
